spring.application.name=speakflow-backend

spring.datasource.url=${AIVEN_DB_URL}
spring.datasource.username=${AIVEN_DB_USERNAME}
spring.datasource.password=${AIVEN_DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=${GEMINI_API_KEY}

server.port=${PORT:8080}